apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleettrack
  labels:
    app: fleettrack
spec:
  replicas: 1
  template:
    metadata:
      name: fleettrack
      labels:
        app: fleettrack
    spec:
      containers:
        - name: fleettrack
          image: com.gmail.olehfursovych/fleettrack:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: fleettrack
